version: "3"

services:
  postgres-keycloak:
    image: postgres
    volumes:
      - postgres-data-keycloak:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  keycloak:
    image: keycloak-chpqa
    environment:
      JAVA_OPTS: "-server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true"
      STARTUP_COMMAND: start-dev
      KC_HTTP_PORT: 8080
      KC_HOSTNAME: localhost
      KC_DB_SCHEMA: public
      KC_DB_URL_HOST: postgres-keycloak
      KC_DB_URL_DATABASE: ${KC_DB_URL_DATABASE}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_LOG_LEVEL: INFO
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      CHPQA_REALM_DISPLAY_NAME: CHPQA-dev
      CHPQA_WEB_APP_URL: ${CHPQA_WEB_APP_URL}
      CHPQA_API_APP_URL: ${CHPQA_API_APP_URL}
      CHPQA_WEB_APP_LOCALHOST_URL: ${CHPQA_WEB_APP_LOCALHOST_URL}
      CHPQA_API_CLIENT_SECRET: ${CHPQA_API_CLIENT_SECRET}
      MAIL_TLS:
      MAIL_AUTH:
      MAIL_PORT: 1025
      MAIL_HOST: mailpit
      MAIL_FROM: no-reply@keycloack.org
      MAIL_SSL:
      MAIL_USER:
      MAIL_PASSWORD:
    ports:
      - 8091:8080
    depends_on:
      - postgres-keycloak

volumes:
  postgres-data-keycloak:
    driver: local
