import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { environment } from 'src/environments/environment.pipeline';

@Injectable({
  providedIn: 'root'
})
export class CountiesService {

  constructor(private http: HttpClient) { }

  private URL = `${environment.baseUrl}/desnz_counties?$select=desnz_name`;

  fetchAll(){
    const auth_token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlhSdmtvOFA3QTNVYVdTblU3Yk05blQwTWpoQSIsImtpZCI6IlhSdmtvOFA3QTNVYVdTblU3Yk05blQwTWpoQSJ9.eyJhdWQiOiJodHRwczovL3VuaWNybXRlc3QuYXBpLmNybTQuZHluYW1pY3MuY29tIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvNzZmOTAzN2QtMGI3My00YTQxLWJjYWMtY2JjY2QxZjFjNDEyLyIsImlhdCI6MTcxMTYzNDkwMSwibmJmIjoxNzExNjM0OTAxLCJleHAiOjE3MTE2MzkwNzUsImFjY3QiOjAsImFjciI6IjEiLCJhaW8iOiJBVlFBcS84V0FBQUE0cXdxT3BsL0RxRTFnN3ppd2ViOHR1MkI0RWpvSmw5cmE1UktVVFNPb1owR2JWYmlmWmJoSmhXR1BwK2RuNmtuVHU1MWxpeE5veFhIbGU5WGRUYU5VTWdyMG5FWFVzSXNqcXYrVktnL3RMQT0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiNTFmODE0ODktMTJlZS00YTllLWFhYWUtYTI1OTFmNDU5ODdkIiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJSb2RvcG91bG9zIiwiZ2l2ZW5fbmFtZSI6Ik9yZmVmcyIsImlwYWRkciI6IjE5NC4yMTkuOTEuMiIsImxvZ2luX2hpbnQiOiJPLkNpUmhObUV5TnpaaU55MDNZbVpoTFRRNVpHSXRPVEZoWVMwM1pUVTJPREU1T1dJeU1qQVNKRGMyWmprd016ZGtMVEJpTnpNdE5HRTBNUzFpWTJGakxXTmlZMk5rTVdZeFl6UXhNaG9aVW05a2IzQnZkV3h2YzA5QWRXNXBjM2x6ZEdWdGN5NW5jaUNEQVE9PSIsIm5hbWUiOiJSb2RvcG91bG9zIE9yZmVmcyIsIm9pZCI6ImE2YTI3NmI3LTdiZmEtNDlkYi05MWFhLTdlNTY4MTk5YjIyMCIsIm9ucHJlbV9zaWQiOiJTLTEtNS0yMS0zNDYxNzM1Ni00NTA4ODc3MjYtNDAyMDI4NjE0LTIxNzIzIiwicHVpZCI6IjEwMDMyMDAzNUUwOTM1QjQiLCJyaCI6IjAuQVFrQWZRUDVkbk1MUVVxOHJNdk0wZkhFRWdjQUFBQUFBQUFBd0FBQUFBQUFBQUFKQUFvLiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6IjdfcVBwUld1QkcyM0dXZzBuN18xZWFySHYtU3gyS0l6RFFsQzN2UTVnZlkiLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiRVUiLCJ0aWQiOiI3NmY5MDM3ZC0wYjczLTRhNDEtYmNhYy1jYmNjZDFmMWM0MTIiLCJ1bmlxdWVfbmFtZSI6IlJvZG9wb3Vsb3NPQHVuaXN5c3RlbXMuZ3IiLCJ1cG4iOiJSb2RvcG91bG9zT0B1bmlzeXN0ZW1zLmdyIiwidXRpIjoiakFfdHJnZFhqMGlxVmtxRFhWM2FBQSIsInZlciI6IjEuMCIsInhtc19jYWUiOiIxIn0.f58dMX5vUDI285kxjA7p-nZ44H96vIUNF1KamXCl4zika08izLB0mGBmM95OV3bq5Yg2OEYv1oHxVcPOTLThJxO_Haji8J5fJj_wIq0OILxygcvCieFkaT8inlFF9dF2h046zTZ4LT5mFLNgl_Mc-BKlzdsx3WOJiw0UwvYo0JTgix-NLrLU2iP_olM1xc5uo4f_K4rWEkVXb-XKW4BXPm6mPo495_bfZhrgKMh7Nsk2HvjkqPC6vQXIzerLiwmaXMAD5oi6M7pxnwWA521yAv6SG10QZhYlQkKKTNr5Lj5dg1ZuqwIL1uUihueiyE-gW4-uN2gvmOQBQdr3nSxRng';
    const headers = new HttpHeaders({
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${auth_token}`
    });
    return this.http.get(this.URL, { headers });
  }
}
